name: sample
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Sample"
        run: echo ${{ secrets.SIGNING_KEY_BASE64_FOR_BUNDLE　}}
  

      - name: "Sample2"
        run: echo abcdefg
